# Generated by Django 5.0.9 on 2026-04-10 16:32

import apps.findings.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("controls", "0001_initial"),
        ("engagements", "0001_initial"),
        ("risks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the finding."),
                ),
                (
                    "finding_type",
                    models.CharField(
                        choices=[
                            ("control_deficiency", "Control Deficiency"),
                            ("process_gap", "Process Gap"),
                            ("compliance_issue", "Compliance Issue"),
                            ("fraud_indicator", "Fraud Indicator"),
                            ("observation", "Observation"),
                            ("best_practice", "Best Practice Recommendation"),
                        ],
                        default="control_deficiency",
                        max_length=25,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Informational"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("in_remediation", "In Remediation"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("risk_accepted", "Risk Accepted"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("root_cause", models.TextField(blank=True)),
                (
                    "management_response",
                    models.TextField(
                        blank=True,
                        help_text="Response from management regarding this finding.",
                    ),
                ),
                ("identified_date", models.DateField(blank=True, null=True)),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Target remediation date.", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "control",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="findings",
                        to="controls.control",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_findings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="engagements.auditengagement",
                    ),
                ),
                (
                    "identified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="identified_findings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person responsible for remediation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_findings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="findings",
                        to="risks.risk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finding",
                "verbose_name_plural": "Findings",
                "db_table": "findings_finding",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("workpaper", "Workpaper"),
                            ("screenshot", "Screenshot"),
                            ("document", "Document"),
                            ("spreadsheet", "Spreadsheet"),
                            ("email", "Email"),
                            ("photo", "Photo"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="document",
                        max_length=20,
                    ),
                ),
                (
                    "sharepoint_url",
                    models.URLField(
                        blank=True,
                        help_text="SharePoint document URL (alternative to file upload).",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.findings.models._evidence_upload_path,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        default=0, help_text="Size in bytes."
                    ),
                ),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_files",
                        to="engagements.auditengagement",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidence_files",
                        to="engagements.audittask",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_files",
                        to="findings.finding",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidence",
                "verbose_name_plural": "Evidence Files",
                "db_table": "findings_evidence",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="RemediationAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("completion_notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_remediation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remediation_actions",
                        to="findings.finding",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_remediation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Remediation Action",
                "verbose_name_plural": "Remediation Actions",
                "db_table": "findings_remediation_action",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("finding", "Finding"),
                            ("report", "Audit Report"),
                            ("engagement", "Audit Engagement"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(help_text="UUID of the object being approved."),
                ),
                ("entity_name", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("request_notes", models.TextField(blank=True)),
                ("review_notes", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Request",
                "verbose_name_plural": "Approval Requests",
                "db_table": "findings_approval_request",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="findings_ap_entity__eb4140_idx",
                    ),
                    models.Index(
                        fields=["approver", "status"],
                        name="findings_ap_approve_9a9413_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["engagement", "severity"], name="findings_fi_engagem_2f4427_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["status", "severity"], name="findings_fi_status_88377b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(fields=["owner"], name="findings_fi_owner_i_53d02e_idx"),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["due_date"], name="findings_fi_due_dat_5d5851_idx"
            ),
        ),
    ]
