# Generated by Django 5.0.9 on 2026-04-10 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="remediationaction",
            name="evidence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remediation_actions",
                to="findings.evidence",
            ),
        ),
    ]
