# Generated by Django 5.0.9 on 2026-04-10 16:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("engagements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Risk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("financial", "Financial"),
                            ("compliance", "Compliance"),
                            ("strategic", "Strategic"),
                            ("reputational", "Reputational"),
                            ("technology", "Technology"),
                            ("fraud", "Fraud"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="operational",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("identified", "Identified"),
                            ("assessed", "Assessed"),
                            ("mitigated", "Mitigated"),
                            ("accepted", "Accepted"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="identified",
                        max_length=20,
                    ),
                ),
                (
                    "inherent_likelihood",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="1=Rare, 5=Almost certain",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "inherent_impact",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="1=Negligible, 5=Catastrophic",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "residual_likelihood",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "residual_impact",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("treatment_plan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_objective",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risks",
                        to="core.businessobjective",
                    ),
                ),
                (
                    "business_process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risks",
                        to="core.businessprocess",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk",
                "verbose_name_plural": "Risks",
                "db_table": "risks_risk",
                "ordering": ["-inherent_likelihood", "-inherent_impact"],
            },
        ),
        migrations.CreateModel(
            name="EngagementRisk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assessment_notes", models.TextField(blank=True)),
                ("is_in_scope", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_engagement_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_risks",
                        to="engagements.auditengagement",
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_risks",
                        to="risks.risk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Engagement Risk",
                "verbose_name_plural": "Engagement Risks",
                "db_table": "risks_engagement_risk",
            },
        ),
        migrations.AddIndex(
            model_name="risk",
            index=models.Index(
                fields=["category", "status"], name="risks_risk_categor_52cd9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="risk",
            index=models.Index(fields=["owner"], name="risks_risk_owner_i_01937c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="engagementrisk",
            unique_together={("engagement", "risk")},
        ),
    ]
