# Generated by Django 5.0.9 on 2026-04-10 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEngagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("in_progress", "In Progress"),
                            ("review", "Under Review"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="planning",
                        max_length=20,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        help_text="Audit period (e.g. 'Q1 2026', 'FY2025', 'Jan–Mar 2026').",
                        max_length=100,
                    ),
                ),
                (
                    "scope",
                    models.TextField(
                        blank=True, help_text="What is included/excluded."
                    ),
                ),
                (
                    "objectives",
                    models.TextField(
                        blank=True, help_text="Stated goals of this engagement."
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audit_manager",
                    models.ForeignKey(
                        help_text="Responsible audit manager.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_engagements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business_objective",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="engagements",
                        to="core.businessobjective",
                    ),
                ),
                (
                    "business_process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="engagements",
                        to="core.businessprocess",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_engagements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Engagement",
                "verbose_name_plural": "Audit Engagements",
                "db_table": "engagements_audit_engagement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("review", "Under Review"),
                            ("done", "Done"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="todo",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "escalation_flag",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True when this task needs escalation attention.",
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="engagements.auditengagement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Task",
                "verbose_name_plural": "Audit Tasks",
                "db_table": "engagements_audit_task",
                "ordering": ["due_date", "priority"],
            },
        ),
        migrations.CreateModel(
            name="EngagementAuditor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role_note",
                    models.CharField(
                        blank=True,
                        help_text="Optional note on this auditor's specific role.",
                        max_length=200,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditor_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "auditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_auditors",
                        to="engagements.auditengagement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Engagement Auditor",
                "verbose_name_plural": "Engagement Auditors",
                "db_table": "engagements_engagement_auditor",
            },
        ),
        migrations.AddIndex(
            model_name="auditengagement",
            index=models.Index(fields=["status"], name="engagements_status_384266_idx"),
        ),
        migrations.AddIndex(
            model_name="auditengagement",
            index=models.Index(
                fields=["audit_manager"], name="engagements_audit_m_b16eae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditengagement",
            index=models.Index(
                fields=["start_date", "end_date"], name="engagements_start_d_7b03b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittask",
            index=models.Index(
                fields=["engagement", "status"], name="engagements_engagem_06a884_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittask",
            index=models.Index(
                fields=["assigned_to", "status"], name="engagements_assigne_b6e95f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="engagementauditor",
            unique_together={("engagement", "auditor")},
        ),
    ]
