# Generated by Django 5.0.9 on 2026-04-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagementauditor",
            name="role_key",
            field=models.CharField(
                default="RoleKey1",
                help_text="'RoleKey0' = Lead Auditor, 'RoleKey1' = Team Member.",
                max_length=20,
            ),
        ),
    ]
