# Generated by Django 5.0.9 on 2026-04-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="testexception",
            new_name="testing_exc_excepti_33b49b_idx",
            old_name="testing_exc_type_severity_idx",
        ),
        migrations.RenameIndex(
            model_name="testexception",
            new_name="testing_exc_test_in_1311bf_idx",
            old_name="testing_exc_instance_sev_idx",
        ),
        migrations.RenameIndex(
            model_name="testinstance",
            new_name="testing_tes_operati_7f18ca_idx",
            old_name="testing_ti_oe_status_idx",
        ),
        migrations.RenameIndex(
            model_name="testplan",
            new_name="testing_tes_control_06a3c6_idx",
            old_name="testing_tp_control_status_idx",
        ),
        migrations.RenameIndex(
            model_name="testplan",
            new_name="testing_tes_engagem_26ca48_idx",
            old_name="testing_tp_engagement_status_idx",
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="conclusion",
            field=models.TextField(
                blank=True, help_text="Narrative conclusion of the test instance."
            ),
        ),
        migrations.AlterField(
            model_name="testplan",
            name="planned_date",
            field=models.DateField(
                blank=True, help_text="Target date for completing the test.", null=True
            ),
        ),
    ]
