# Generated by Django 5.0.9 on 2026-04-12 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0003_control_testing_fields"),
        ("testing", "0002_control_testing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="sampleitem",
            name="population_segment",
            field=models.CharField(
                blank=True,
                help_text="Stratum label for stratified sampling (e.g. 'High Value', 'Q1').",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="sampleitem",
            name="tested_date",
            field=models.DateField(
                blank=True,
                help_text="Date this specific sample item was tested.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="testexception",
            name="root_cause",
            field=models.CharField(
                blank=True,
                choices=[
                    ("process", "Process"),
                    ("system", "System"),
                    ("people", "People"),
                    ("control_design", "Control Design"),
                    ("data", "Data"),
                    ("external", "External"),
                    ("other", "Other"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="testinstance",
            name="engagement_control",
            field=models.ForeignKey(
                blank=True,
                help_text="The engagement control record this instance rolls up to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_instances",
                to="controls.engagementcontrol",
            ),
        ),
        migrations.AddField(
            model_name="testplan",
            name="acceptance_criteria",
            field=models.TextField(
                blank=True,
                help_text="What constitutes a pass or fail for this test plan.",
            ),
        ),
        migrations.AddField(
            model_name="testplan",
            name="procedure_template",
            field=models.TextField(
                blank=True,
                help_text="Standard test steps to be followed during execution.",
            ),
        ),
        migrations.AddField(
            model_name="testplan",
            name="tolerable_exception_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Max acceptable exception rate as a percentage (e.g. 5.00). Null = zero tolerance.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
