# Generated by Django 5.0.9 on 2026-04-10 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("engagements", "0001_initial"),
        ("risks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Control",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "control_type",
                    models.CharField(
                        choices=[
                            ("preventive", "Preventive"),
                            ("detective", "Detective"),
                            ("corrective", "Corrective"),
                            ("directive", "Directive"),
                            ("compensating", "Compensating"),
                        ],
                        db_index=True,
                        default="preventive",
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("continuous", "Continuous"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annually", "Annually"),
                            ("ad_hoc", "Ad-Hoc"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("design_deficiency", "Design Deficiency"),
                            ("under_review", "Under Review"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "control_reference",
                    models.CharField(
                        blank=True,
                        help_text="Internal control ID / framework reference (e.g. ISO 27001 A.9.1.1).",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controls",
                        to="core.businessprocess",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_controls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_controls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "risks",
                    models.ManyToManyField(
                        blank=True, related_name="controls", to="risks.risk"
                    ),
                ),
            ],
            options={
                "verbose_name": "Control",
                "verbose_name_plural": "Controls",
                "db_table": "controls_control",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EngagementControl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "test_procedure",
                    models.TextField(
                        blank=True, help_text="Steps taken to test this control."
                    ),
                ),
                (
                    "test_result",
                    models.CharField(
                        choices=[
                            ("not_tested", "Not Tested"),
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("partial", "Partial"),
                            ("na", "N/A"),
                        ],
                        default="not_tested",
                        max_length=20,
                    ),
                ),
                (
                    "effectiveness_rating",
                    models.CharField(
                        choices=[
                            ("effective", "Effective"),
                            ("partially_effective", "Partially Effective"),
                            ("ineffective", "Ineffective"),
                            ("not_assessed", "Not Assessed"),
                        ],
                        default="not_assessed",
                        max_length=25,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("tested_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_controls",
                        to="controls.control",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_engagement_controls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_controls",
                        to="engagements.auditengagement",
                    ),
                ),
                (
                    "tested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Engagement Control",
                "verbose_name_plural": "Engagement Controls",
                "db_table": "controls_engagement_control",
            },
        ),
        migrations.AddIndex(
            model_name="control",
            index=models.Index(
                fields=["control_type", "status"], name="controls_co_control_cc4103_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="control",
            index=models.Index(fields=["owner"], name="controls_co_owner_i_2f8efc_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="engagementcontrol",
            unique_together={("engagement", "control")},
        ),
    ]
