# Generated by Django 5.0.9 on 2026-04-10 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0001_initial"),
        ("risks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagementcontrol",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Display label, e.g. 'Control Name – Risk Name'.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="engagementcontrol",
            name="engagement_risk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="engagement_controls",
                to="risks.engagementrisk",
            ),
        ),
    ]
