# Generated by Django 5.0.9 on 2026-04-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0002_engagementcontrol_display_name_and_more"),
        ("testing", "0002_control_testing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="control",
            name="assertions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Audit assertions this control addresses.",
                related_name="controls",
                to="testing.assertiontype",
            ),
        ),
        migrations.AddField(
            model_name="control",
            name="execution_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual", "Manual"),
                    ("automated", "Automated"),
                    ("hybrid", "Hybrid"),
                ],
                default="manual",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="control",
            name="is_key_control",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is a key control (key controls receive higher testing priority).",
            ),
        ),
    ]
