# Generated by Django 5.0.9 on 2026-04-13 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditPlanSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(unique=True)),
                ("planned_audits", models.IntegerField(default=0)),
                ("mar_required_count", models.IntegerField(default=0)),
                ("non_mar_count", models.IntegerField(default=0)),
                (
                    "avg_priority_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("estimated_total_hours", models.IntegerField(default=0)),
                ("coverage_notes", models.TextField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Audit Plan Summary",
                "verbose_name_plural": "Audit Plan Summaries",
                "db_table": "audit_plan_summary",
                "ordering": ["fiscal_year"],
            },
        ),
        migrations.CreateModel(
            name="ControlEffectivenessScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="0.00–1.00",
                        max_digits=4,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="e.g. Fully Effective", max_length=50),
                ),
                ("meaning", models.TextField()),
                ("typical_signal", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Control Effectiveness Scale",
                "verbose_name_plural": "Control Effectiveness Scales",
                "db_table": "audit_plan_control_effectiveness_scale",
                "ordering": ["-score"],
            },
        ),
        migrations.CreateModel(
            name="GRCTestingTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "layer",
                    models.CharField(
                        db_index=True,
                        help_text="GOVERNANCE, OPERATIONS, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="e.g. GOV-1  Enterprise & IT Governance",
                        max_length=100,
                    ),
                ),
                (
                    "sub_theme_code",
                    models.CharField(help_text="e.g. GOV-1.1", max_length=20),
                ),
                (
                    "sub_theme_name",
                    models.CharField(
                        help_text="e.g. Organizational Strategy & Mission",
                        max_length=200,
                    ),
                ),
                ("control_count", models.IntegerField(blank=True, null=True)),
                (
                    "control_types",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("key_evidence", models.TextField(blank=True, null=True)),
                (
                    "planned_audit_years",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GRC Testing Theme",
                "verbose_name_plural": "GRC Testing Themes",
                "db_table": "audit_plan_grc_testing_theme",
                "ordering": ["layer", "sub_theme_code"],
            },
        ),
        migrations.CreateModel(
            name="MARTestingEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(default=2031)),
                (
                    "mar_test_area",
                    models.CharField(
                        help_text="e.g. ICFR — Financial Close & Reporting",
                        max_length=200,
                    ),
                ),
                ("control_theme", models.CharField(max_length=200)),
                ("control_count", models.IntegerField(blank=True, null=True)),
                ("au_scope", models.TextField(blank=True, null=True)),
                (
                    "test_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Design + Effectiveness", "Design + Effectiveness"),
                            ("Effectiveness", "Effectiveness"),
                            ("Inspection", "Inspection"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("sample_size", models.IntegerField(blank=True, null=True)),
                ("quarter", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "assigned_to",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("estimated_hours", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "MAR Testing Engagement",
                "verbose_name_plural": "MAR Testing Engagements",
                "db_table": "audit_plan_mar_testing_engagement",
                "ordering": ["fiscal_year", "mar_test_area"],
            },
        ),
        migrations.CreateModel(
            name="RiskScoringConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "factor",
                    models.CharField(help_text="e.g. Financial Impact", max_length=100),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, help_text="e.g. 0.30 for 30%", max_digits=5
                    ),
                ),
                ("score_1_label", models.CharField(max_length=200)),
                ("score_2_label", models.CharField(max_length=200)),
                ("score_3_label", models.CharField(max_length=200)),
                ("score_4_label", models.CharField(max_length=200)),
                ("score_5_label", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Risk Scoring Config",
                "verbose_name_plural": "Risk Scoring Configs",
                "db_table": "audit_plan_risk_scoring_config",
                "ordering": ["-weight"],
            },
        ),
        migrations.CreateModel(
            name="AuditableEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "au_id",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. AU-070",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("Cybersecurity", "Cybersecurity"),
                            ("Business Continuity", "Business Continuity"),
                            ("Claims", "Claims"),
                            ("Third-Party Risk", "Third-Party Risk"),
                            ("Financial Reporting", "Financial Reporting"),
                            ("Actuarial / ERM", "Actuarial / ERM"),
                            ("IT Infrastructure", "IT Infrastructure"),
                            ("IT / SDLC", "IT / SDLC"),
                            ("ERM / Governance", "ERM / Governance"),
                            ("Claims / Fraud", "Claims / Fraud"),
                            ("Claims/UW/Agency", "Claims/UW/Agency"),
                            ("Underwriting", "Underwriting"),
                            ("Data Governance", "Data Governance"),
                            ("Compliance", "Compliance"),
                            ("HR", "HR"),
                            ("Actuarial", "Actuarial"),
                            ("Market Conduct", "Market Conduct"),
                            ("Legal / Governance", "Legal / Governance"),
                            ("IT Asset Mgmt", "IT Asset Mgmt"),
                            ("Operations", "Operations"),
                            ("IT Operations", "IT Operations"),
                            ("Policy Admin", "Policy Admin"),
                            ("Physical Security", "Physical Security"),
                            ("Governance", "Governance"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "rank",
                    models.IntegerField(
                        blank=True, help_text="Priority rank from plan", null=True
                    ),
                ),
                (
                    "priority_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "residual_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Critical", "Critical"),
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        db_index=True,
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "mar_required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether MAR testing is required for this AU",
                    ),
                ),
                (
                    "primary_clusters",
                    models.CharField(
                        blank=True,
                        help_text="e.g. GS-02, SC-01, AC-02",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "frameworks",
                    models.CharField(
                        blank=True,
                        help_text="e.g. NIST CSF 2.0, Iowa 507E, SOC 2",
                        max_length=300,
                        null=True,
                    ),
                ),
                ("risk_count", models.IntegerField(blank=True, null=True)),
                (
                    "key_control_ids",
                    models.TextField(
                        blank=True, help_text="Comma-separated CTL IDs", null=True
                    ),
                ),
                ("agile_scope", models.TextField(blank=True, null=True)),
                ("estimated_hours", models.IntegerField(blank=True, null=True)),
                (
                    "erm_risk_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "risk_appetite_threshold",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "exceeds_appetite",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "frequency_override_triggers",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Auditable Entity",
                "verbose_name_plural": "Auditable Entities",
                "db_table": "audit_plan_auditable_entity",
                "ordering": ["rank", "au_id"],
                "indexes": [
                    models.Index(
                        fields=["domain", "residual_level"],
                        name="audit_plan__domain_e3b899_idx",
                    ),
                    models.Index(
                        fields=["mar_required"], name="audit_plan__mar_req_b954a2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="KeyControlAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "control_id",
                    models.CharField(
                        db_index=True, help_text="e.g. CTL-285", max_length=20
                    ),
                ),
                (
                    "is_key_control",
                    models.BooleanField(
                        default=False,
                        help_text="★ flag — key control for reliance testing",
                    ),
                ),
                ("control_name", models.CharField(max_length=300)),
                ("framework", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "layer",
                    models.CharField(
                        blank=True,
                        help_text="GOVERNANCE, OPERATIONS, etc.",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("grc_domain", models.CharField(blank=True, max_length=100, null=True)),
                ("grc_theme", models.CharField(blank=True, max_length=100, null=True)),
                ("sub_area", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "control_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Directive", "Directive"),
                            ("Preventive", "Preventive"),
                            ("Detective", "Detective"),
                            ("Corrective", "Corrective"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Administrative", "Administrative"),
                            ("Technical", "Technical"),
                            ("Physical", "Physical"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Annual", "Annual"),
                            ("Quarterly", "Quarterly"),
                            ("Monthly", "Monthly"),
                            ("Continuous", "Continuous"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("plan_year", models.IntegerField(blank=True, null=True)),
                (
                    "control_tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Tier 1 (MAR/Fin Rptg)", "Tier 1 (MAR/Fin Rptg)"),
                            ("Tier 2 (Key Ops/Reg)", "Tier 2 (Key Ops/Reg)"),
                            ("Tier 3 (Supporting)", "Tier 3 (Supporting)"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("baseline_complete", models.BooleanField(default=False)),
                (
                    "control_effectiveness",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="0.00–1.00",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("reliance_ready", models.BooleanField(default=False)),
                (
                    "testing_strategy",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_au",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_controls",
                        to="audit_plan.auditableentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Key Control Assignment",
                "verbose_name_plural": "Key Control Assignments",
                "db_table": "audit_plan_key_control_assignment",
                "ordering": ["control_id"],
            },
        ),
        migrations.CreateModel(
            name="ControlRelianceCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycle_year", models.IntegerField(help_text="2026, 2027, or 2028")),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Clean", "Clean"),
                            ("Exceptions", "Exceptions"),
                            ("Not Tested", "Not Tested"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reliance_cycles",
                        to="audit_plan.keycontrolassignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Control Reliance Cycle",
                "verbose_name_plural": "Control Reliance Cycles",
                "db_table": "audit_plan_control_reliance_cycle",
                "ordering": ["control", "cycle_year"],
            },
        ),
        migrations.CreateModel(
            name="AuditPlanYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fiscal_year",
                    models.IntegerField(db_index=True, help_text="2026–2031"),
                ),
                (
                    "planned_year",
                    models.IntegerField(
                        blank=True,
                        help_text="The year this AU is actually scheduled",
                        null=True,
                    ),
                ),
                (
                    "quarter",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Q1", "Q1"),
                            ("Q2", "Q2"),
                            ("Q3", "Q3"),
                            ("Q4", "Q4"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("In Progress", "In Progress"),
                            ("Complete", "Complete"),
                            ("Deferred", "Deferred"),
                        ],
                        db_index=True,
                        default="Not Started",
                        max_length=15,
                    ),
                ),
                (
                    "is_scheduled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the AU appears in this fiscal year (● marker)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "au",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_years",
                        to="audit_plan.auditableentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Plan Year",
                "verbose_name_plural": "Audit Plan Years",
                "db_table": "audit_plan_year",
                "ordering": ["fiscal_year", "au__rank"],
                "unique_together": {("au", "fiscal_year")},
            },
        ),
        migrations.AddIndex(
            model_name="keycontrolassignment",
            index=models.Index(
                fields=["control_tier", "plan_year"],
                name="audit_plan__control_11fdb3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="keycontrolassignment",
            index=models.Index(
                fields=["is_key_control", "reliance_ready"],
                name="audit_plan__is_key__942db9_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="controlreliancecycle",
            unique_together={("control", "cycle_year")},
        ),
    ]
