# Generated by Django 5.0.9 on 2026-04-10 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engagements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditReportTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "sharepoint_template_url",
                    models.URLField(
                        blank=True,
                        help_text="SharePoint URL where the source template document is stored.",
                    ),
                ),
                (
                    "content_template",
                    models.TextField(
                        help_text="Report template body. Supports Markdown. Use {{engagement_name}}, {{audit_manager}}, {{findings_summary}} etc. as placeholders."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_report_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Report Template",
                "verbose_name_plural": "Audit Report Templates",
                "db_table": "reports_audit_report_template",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AuditReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("executive_summary", models.TextField(blank=True)),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Full report content (Markdown supported).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("final", "Final"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "distribution_list",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated email addresses of report recipients.",
                    ),
                ),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sharepoint_report_url",
                    models.URLField(
                        blank=True,
                        help_text="SharePoint URL where the finalised report document is stored.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="engagements.auditengagement",
                    ),
                ),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finalized_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="reports.auditreporttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Report",
                "verbose_name_plural": "Audit Reports",
                "db_table": "reports_audit_report",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["engagement", "status"],
                        name="reports_aud_engagem_74f817_idx",
                    )
                ],
            },
        ),
    ]
