from django.urls import path

from .views import (
    AssertionTypeDetailView,
    AssertionTypeListCreateView,
    SampleItemDetailView,
    SampleItemListCreateView,
    TestExceptionDetailView,
    TestExceptionEscalateView,
    TestExceptionListCreateView,
    TestInstanceConcludeView,
    TestInstanceDetailView,
    TestInstanceExceptionListCreateView,
    TestInstanceListCreateView,
    TestInstanceSampleListCreateView,
    TestInstanceStatisticsView,
    TestPlanDetailView,
    TestPlanInstanceListCreateView,
    TestPlanListCreateView,
    TestingMethodDetailView,
    TestingMethodListCreateView,
)

urlpatterns = [
    path("testing-methods/", TestingMethodListCreateView.as_view(), name="testing-method-list"),
    path("testing-methods/<uuid:pk>/", TestingMethodDetailView.as_view(), name="testing-method-detail"),
    path("assertion-types/", AssertionTypeListCreateView.as_view(), name="assertion-type-list"),
    path("assertion-types/<uuid:pk>/", AssertionTypeDetailView.as_view(), name="assertion-type-detail"),
    path("test-plans/", TestPlanListCreateView.as_view(), name="test-plan-list"),
    path("test-plans/<uuid:pk>/", TestPlanDetailView.as_view(), name="test-plan-detail"),
    path("test-plans/<uuid:pk>/instances/", TestPlanInstanceListCreateView.as_view(), name="test-plan-instances"),
    path("test-instances/", TestInstanceListCreateView.as_view(), name="test-instance-list"),
    path("test-instances/<uuid:pk>/", TestInstanceDetailView.as_view(), name="test-instance-detail"),
    path("test-instances/<uuid:pk>/samples/", TestInstanceSampleListCreateView.as_view(), name="test-instance-samples"),
    path("test-instances/<uuid:pk>/exceptions/", TestInstanceExceptionListCreateView.as_view(), name="test-instance-exceptions"),
    path("test-instances/<uuid:pk>/conclude/", TestInstanceConcludeView.as_view(), name="test-instance-conclude"),
    path("test-instances/<uuid:pk>/statistics/", TestInstanceStatisticsView.as_view(), name="test-instance-statistics"),
    path("sample-items/", SampleItemListCreateView.as_view(), name="sample-item-list"),
    path("sample-items/<uuid:pk>/", SampleItemDetailView.as_view(), name="sample-item-detail"),
    path("test-exceptions/", TestExceptionListCreateView.as_view(), name="test-exception-list"),
    path("test-exceptions/<uuid:pk>/", TestExceptionDetailView.as_view(), name="test-exception-detail"),
    path("test-exceptions/<uuid:pk>/escalate/", TestExceptionEscalateView.as_view(), name="test-exception-escalate"),
]
